### ISSUE TITLE
Deprecate KUBE_API_ROOT

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/k8s-exec-plugin#91]
The current KUBE_API_ROOT variable allows the user to specify the exact API version for the plugin to use. e.g. `http://api-url:8080/api/vX"

We don't actually want to allow the user to configure the API version, since the plugin is written to support a specific version (currently v1).

The information that the user does need to provide:
- IP address / hostname for the apiserver
- Protocol (HTTP vs HTTPS)
- Port (8080, 443, something else?)

**Comment by altvnk** [comment]
I vote for certificate auth instead of tokens or at least both. For now it's default way to auth in kubernetes API via service account.
